### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by dahaigui** [dblhlx/PyBSASeq#3]
Got an error when loaded GATK result with PyBSASeq BulksOnly script.

`Perform SNP filtering
Traceback (most recent call last):
  File "/data/mg1/chenhx/software/PyBSASeq/BulksOnly/PyBSASeq.py", line 993, in <module>
    bsaSNPs = snpFiltering(snpRawDF)
  File "/data/mg1/chenhx/software/PyBSASeq/BulksOnly/PyBSASeq.py", line 112, in snpFiltering
    df_lowq = df[(df[fb_GQ]<gqValue) | (df[sb_GQ]<gqValue)]
  File "/data/mg1/chenhx/miniconda3/lib/python3.6/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/data/mg1/chenhx/miniconda3/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 370, in wrapper
    res_values = comparison_op(lvalues, rvalues, op)
  File "/data/mg1/chenhx/miniconda3/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 244, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/data/mg1/chenhx/miniconda3/lib/python3.6/site-packages/pandas/core/ops/array_ops.py", line 56, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 103, in pandas._libs.ops.scalar_compare
TypeError: '<' not supported between instances of 'str' and 'int'`

**Comment by dblhlx** [comment]
Sorry for the late replay. I didn't receive any email notification of this issue from github.

Would you please send me a small subset of your data?

**Comment by dblhlx** [comment]
@dahaigui, what variable type is the GQ value in your dataset. It is float in my dataset.

**Comment by dblhlx** [comment]
I'll close this issue since I haven't heard from you for a long time. Please reopen it if you still have this problem. Please attach a thousand rows of your data in case you reopen this issue.
